### PR TITLE
Add GET endpoint and deserialize more info about builds

### PR DESCRIPTION
**Pull request by pchico83**
This PR adds support for getting a given build without waiting for a particular status.
It also adds more fields to `Workflow`object.

### CODE REVIEW

**Comment by olegsu** [comment]
Thanks @pchico83 , please also patch the version file.

**Comment by pchico83** [comment]
@olegsu I want to add support for querying the logs too.
Should I patch the version for each PR? or do you prefer a single PR?

**Comment by olegsu** [comment]
@pchico83 lets have it in different pr's

**Comment by pchico83** [comment]
@olegsu cool
and one version patch for each PR? or only for the second one?

**Comment by olegsu** [comment]
For each PR that should be marked as sdk release.
In that case, I think for each pr

**Comment by pchico83** [comment]
@olegsu updated

**Pull request merged**
